name: My Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run My Action
        run: |
          # Use the environment variable in your action
          echo "My secret API key is: ${{ secrets.MY_SECRET_API_KEY }}"
