name: Main Workflow

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Trigger Reusable Workflow
        uses: ./.github/workflows/conditionalPipeline.yml
        with:
          NAME: ${{ secrets.NAME }}
