name: My Main Workflow

on:
  push:
    branches:
      - master

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      MY_SECRET_ENV_VARIABLE: ${{ secrets.NAME }} # Set the environment variable
    steps:
      - name: Run My Reusable Workflow
        uses: ./.github/workflows/conditionalPipeline.yml # Path to the reusable workflow file
