name: My Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  my-job:
    uses: ./.github/workflows/conditionalPipeline.yml # Path to the reusable workflow file
    secrets:
      NAME: ${{ secrets.NAME }}
        
